### ISSUE TITLE
有个报错，但是因为是打包后的，我没敢动

### ISSUE THREAD

**Issue by EEEVO** [blue0728/vue-area#11]
代码如下
![default](https://user-images.githubusercontent.com/19979240/31489984-1da8866e-af75-11e7-942a-ef49552d1957.png)

报错信息如下
![image](https://user-images.githubusercontent.com/19979240/31490006-2ead283e-af75-11e7-8b2d-ec21591c7811.png)

情况是我在点击时更改vueAreaShow=true，既直接显示城市选择器，就会有报错信息，我在源demo里面没有排查出来，特来此反馈一下

**Comment by EEEVO** [comment]
把源码文件拿出来跑我找到问题了。第一次进去的时候在watch里面跑了一次，这个时候this.result是空的，传出去我拿了属性，就出问题了。

**Comment by blue0728** [comment]
[新版](https://github.com/blue0728/vue-city-picker)  省市区三级联动 支持自定义城市数据
