### ISSUE TITLE
怎么使用后端返回的数据呢

### ISSUE THREAD

**Issue by zhangliqin** [blue0728/vue-area#12]

**Comment by blue0728** [comment]
查看 https://github.com/blue0728/vue-area/issues/8

**Comment by zhangliqin** [comment]
import {province, city, area} from './city-data'这么写好像是找不到文件

**Comment by zhangliqin** [comment]
给province赋值是会报错   
![1509530535 1](https://user-images.githubusercontent.com/19232228/32269919-de7526d6-bf2e-11e7-8f0a-962d04f925f9.png)
![1509530600 1](https://user-images.githubusercontent.com/19232228/32269953-fb95b924-bf2e-11e7-9673-973e97be6d06.png)

**Comment by blue0728** [comment]
[新版](https://github.com/blue0728/vue-city-picker)  省市区三级联动 支持自定义城市数据
