### ISSUE TITLE
如何把city.js里面的数据换成动态的呢？

### ISSUE THREAD

**Issue by VickyRong** [blue0728/vue-area#8]
你好，最近在使用您的插件做一个小项目，但是在地区联动选择的时候，省市的信息需要动态从后台获取，请问怎么修改插件中请求地区数据的这一部分？如百忙之中能看到解决，十分感谢

**Comment by blue0728** [comment]
你好，
可以把`vue-area.vue` 自己下载下来，作为自己项目的一个组件，
然后把 `import {province, city, area} from './city-data'` 获取的数据，
用`ajax`方式获取，当然注意下格式，和`city-data.js`的保持一致。
重新赋值下`province, city, area`,  当然还需要对源码进行一些修改。

**Comment by VickyRong** [comment]
非常感谢，我现在去试试

**Comment by blue0728** [comment]
@VickyRong 不客气。
受到你的启发，我正好可以加上异步获取数据的配置。
非常感谢。

**Comment by VickyRong** [comment]
根据你的建议已经解决了我的问题～开心😄

**Comment by blue0728** [comment]
[新版](https://github.com/blue0728/vue-city-picker)  省市区三级联动 支持自定义城市数据

**Comment by VickyRong** [comment]
OKOK～厉害厉害
